POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS code rest client is a pretty handy tool",
    "important": true
}

###
GET http://localhost:3001/api/localhost:3001/api/notes