### Correct Token
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InllZXRpdml0eSIsImlkIjoiNjU5YzQ2Njg5MDBlYjcxODUwNDdkY2ZiIiwiaWF0IjoxNzA0NzQ0NzIzfQ.thbIFzkf3luuwAZIcDt81RRbALyGtpdUZHh1ltwIMmY

{
    "title": "New blog 3",
    "author": "Jane Doe",
    "url": "http://janedoeblog.com/",
    "likes": 2,
    "userId": "659c4668900eb7185047dcfb"
}

### Wrong Token
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InllZXRpdml0eSIsImlkIjoiNjU5YzQ2Nj

{
    "title": "Jane Does blog",
    "author": "Jane Doe",
    "url": "http://janedoeblog.com/",
    "likes": 2,
    "userId": "659c4668900eb7185047dcfb"
}

### No Token
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Jane Does blog",
    "author": "Jane Doe",
    "url": "http://janedoeblog.com/",
    "likes": 2,
    "userId": "659c4668900eb7185047dcfb"
}